### ISSUE TITLE
Expect open code

### ISSUE THREAD

**Issue by zysNLP** [JasonForJoy/IMN#1]
Expect open code！

**Comment by JasonForJoy** [comment]
@zysNLP We will release the code after paper acceptance soon. Please keep an eye on our work if you are interested. Thanks.

**Comment by ghost** [comment]
> @zysNLP We will release the code after paper acceptance soon. Please keep an eye on our work if you are interested. Thanks.

It's May now.

**Comment by zysNLP** [comment]
The ACL is almost over, expect open code~
