### ISSUE TITLE
One question about the numbers on the last column of one row

### ISSUE THREAD

**Issue by Ailing-Zou** [JasonForJoy/IMN#10]
![rBAoMF3khvCAfpkTAAFzzRaP30I807](https://user-images.githubusercontent.com/52034091/69929209-2d70c980-14f9-11ea-952a-986cc3c8e0d0.png)

What does the last column standfor? (sometimes NA appears)

**Comment by JasonForJoy** [comment]
@Crystalsudo 
The first column means the context id.
The second column means the context.
The third column means the response id of the correct response. If the context has no correct response, we denote with NA.
The fourth column means the response id of the incorrect response. Similarly, if the context has no incorrect response, we denote with NA.

**Comment by Ailing-Zou** [comment]
Ok, thanks for your kind and accurate reply!
