### ISSUE TITLE
when running bash ubuntu_train.sh, one error is D:\Anaconda\python.exe: can't find '__main__' module in 'D:/'

### ISSUE THREAD

**Issue by Ailing-Zou** [JasonForJoy/IMN#11]
Just as the title describes,  could you please tell me where I make the mistake?

**Comment by JasonForJoy** [comment]
@Crystalsudo 
The codes were all tested under the Ubuntu system 16.04.3.
Maybe you run it under the windows system.

**Comment by Ailing-Zou** [comment]
Ok, thanks for your kind and accurate reply! Wish more wonderful papers from you!
