### ISSUE TITLE
When running python train.py, there is nothing in checkpoints. & GPU use problem

### ISSUE THREAD

**Issue by Ailing-Zou** [JasonForJoy/IMN#12]
OS：Ubuntu 16.04.6 LTS
1.<img width="347" alt="rBAoL13l_oiAK60IAAEiyKz_Jnk844" src="https://user-images.githubusercontent.com/52034091/70107911-e1519080-1682-11ea-9006-b39d35be07b2.png">
When running python train.py, there is nothing in checkpoints, there are some results about accuracy and loss.
<img width="323" alt="rBAoMF3nHZKADyySAAAyq3kTUgw708" src="https://user-images.githubusercontent.com/52034091/70107986-11992f00-1683-11ea-9904-edaa7acb5278.png">
2.
I tried:
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
or 
CUDA_VISIBLE_DEVICES=0 ( The same way with your train.sh)
but my GPU isn't running.
<img width="387" alt="rBAoL13nHkaAaK0kAACsdqqJJeM958" src="https://user-images.githubusercontent.com/52034091/70108147-840a0f00-1683-11ea-99e7-e645e20b491b.png">

Have you ever come across this kind of problem? Look forward to your reply!

**Comment by JasonForJoy** [comment]
@Ailing-Zou 
1. The hyper-parameter "evaluate_every" is set to 1000. So evaluation and saving model are performed every 1000 steps.
2. Setting CUDA_VISIBLE_DEVICES=0 works in my machine.
