### ISSUE TITLE
可以提供应用部分的代码或者推荐相关的repo吗？

### ISSUE THREAD

**Issue by luweishuang** [JasonForJoy/IMN#14]
我想将IMN应用到对话上，即一问一答这样的多轮对话的形式。我改写了 eval.py 里的代码，抽取test.txt 里面的机器人说的话建立responses.txt, 然后给出 query_sentence, 在responses.txt里匹配最高的得分作为应答。我发现这样下来代码速度特别慢，几乎不可用，any ideas?
https://github.com/luweishuang/IMN/blob/master/Ecommerce/model/infer.py

**Comment by JasonForJoy** [comment]
@luweishuang 
你好。目前在IMN上我们还没有尝试在给定多轮对话挑选回复后，继续进行对话的相关实验。
