### ISSUE TITLE
The process get stuck after python eval.py

### ISSUE THREAD

**Issue by Ailing-Zou** [JasonForJoy/IMN#15]
Hi,
I have run ' bash douban_train.sh ' ,  I get some results like  
![image](https://user-images.githubusercontent.com/52034091/70906641-d105c200-2041-11ea-8462-d9ea4592e295.png)

Then the process get stuck after I run ' bash douban_test.sh ' , 
![image](https://user-images.githubusercontent.com/52034091/70906669-dfec7480-2041-11ea-97de-3a569e5f43f3.png)
There is no reason to be stuck because the next line is  
'test_dataset = data_helpers.load_dataset(FLAGS.test_file, vocab, FLAGS.max_utter_len, FLAGS.max_utter_num, response_data)
print('test_pairs: {}'.format(len(test_dataset)))'

**Comment by Ailing-Zou** [comment]
I reloaded this whole process and it begins again.

**Comment by JasonForJoy** [comment]
@Ailing-Zou 
The codes were all tested under the Ubuntu system 16.04.3, tensorflow-gpu 1.4.0 and python 2.7.
Maybe you should check it again.

**Comment by KJGithub2021** [comment]
> @Ailing-Zou The codes were all tested under the Ubuntu system 16.04.3, tensorflow-gpu 1.4.0 and python 2.7. Maybe you should check it again.

@JasonForJoy 
Does that mean that this model would be very slow or have problems running on a windows machine ?
