### ISSUE TITLE
关于responses.txt的句子的疑问

### ISSUE THREAD

**Issue by bringtree** [JasonForJoy/IMN#16]
大神你好， 我想问下 负样例中的
![image](https://user-images.githubusercontent.com/20106478/71539308-442e0300-2975-11ea-9e82-014dd621eccb.png)
红色下划线的id 也是responses.txt的 id索引吗？
我看有些case 好奇怪，感觉他们其实都是正类的。
![image](https://user-images.githubusercontent.com/20106478/71539300-2b255200-2975-11ea-9f3d-bbc05091c634.png)

**Comment by JasonForJoy** [comment]
@bringtree 
这个任务的难点之一就是对话回复的多样性。所谓数据中的正负样例其实是人强加上去的，实际上并没有绝对的正样例，也没有绝对的负样例。
