### ISSUE TITLE
Embedding Glove + word2vec embedding

### ISSUE THREAD

**Issue by Aguiar16** [JasonForJoy/IMN#20]
Good Day to you, Mr. Jia-Chen Gu.
Could you kindly share the code that you used to create this mixed embedding for the task with ubuntu dialog corpus v2?

**Comment by KJGithub2021** [comment]
Hello Mr. Mr. Jia-Chen Gu,
I would also like to request access to this code that creates the word2vec+glove word embeddings for the training data.
Could you kindly share with me ?
