### ISSUE TITLE
Can't achieve the same results in your paper on Douban dataset

### ISSUE THREAD

**Issue by Qianqian-Xie** [JasonForJoy/IMN#5]
Hi Jason, thank you for sharing your source codes. I find the results are much worse than results in your paper on Douban dataset. I feel it is very strange. I just use the default parameter in your code. Could you please help me with that? 
![16_11_28__09_11_2019](https://user-images.githubusercontent.com/12404350/64679878-32504f00-d4af-11e9-9e91-b8d8041a1608.jpg)
![16_12_03__09_11_2019](https://user-images.githubusercontent.com/12404350/64679893-39775d00-d4af-11e9-89e8-c8adf4130f1e.jpg)

**Comment by Qianqian-Xie** [comment]
Sorry, I find that it is caused by data processing. I delete the 'EOS' of contexts previous. I fix it now. Thank you!

**Comment by JasonForJoy** [comment]
@xashely Sorry for the late reply. If you still have some problems, feel free to email me directly.
