### ISSUE TITLE
a little lower results on MAP and MRR

### ISSUE THREAD

**Issue by Sjzwind** [JasonForJoy/IMN#6]
Hi, 
    Thanks for you open code. I tried to reproduce your result in the paper using the code with all parameters unchanged, but I got lower result about 2~3 lower on MAP and MRR with Douban Corpus. Could you tell that after how many epoches that you got the best result and the time it took?

Best wishes,
Sjzwind

**Comment by JasonForJoy** [comment]
@Sjzwind Thanks for your interest in our work. 

The test sets of Ubuntu V1 and Ubuntu V2 are large about 500k and 200k pairs respectively, so results on these two datasets have small variance. However, the test sets of Douban and Ecommerce are small both about 10k pairs, so results on these two datasets have large variance. 

The results reported in our paper are the best one out of several runs under the same configuration. Typically, the model will converge at the 4th or 5th epoch on the Douban dataset.

Feel free to contact me if you still have problems.
