### ISSUE TITLE
关于数据集中的候选response的来源？

### ISSUE THREAD

**Issue by gm0616** [JasonForJoy/IMN#8]
您好，我详细的看了一下您的数据和代码，看到您给到的GoogleDriver里面的数据集格式是utterance + 候选response_id (48107|318604|102642 72282|209105|614088|537827|146615|12490|509973), 我想问一下这些个正例和负例都是怎么来的？ 初次涉猎这个任务，小白问题，望解答~

**Comment by JasonForJoy** [comment]
@Liatwilight 
正样例人工标注，负样例随机采样。

**Comment by gm0616** [comment]
好的，了解啦，多谢解答~
