### ISSUE TITLE
请问可以提供英文部分word2vec词向量训练的代码吗

### ISSUE THREAD

**Issue by dzpdzpdzp** [JasonForJoy/IMN#9]
您好，首先非常感谢您分享的代码。另外请问可以提供英文部分word2vec词向量训练的代码吗？

**Comment by JasonForJoy** [comment]
@dzpdzpdzp 您好。请留下您的邮箱，我邮件发送。

**Comment by Ailing-Zou** [comment]
@JasonForJoy  您好，这边能给我发送一下吗 ，zouailing@oppo.com

**Comment by JasonForJoy** [comment]
@Crystalsudo 脚本已发送，请查收邮箱。

**Comment by Ailing-Zou** [comment]
@JasonForJoy  Received, thanks!

**Comment by dzpdzpdzp** [comment]
> @dzpdzpdzp 您好。请留下您的邮箱，我邮件发送。

dengzhipeng@cqu.edu.cn,非常感谢

**Comment by JasonForJoy** [comment]
@dzpdzpdzp 
脚本已发送，请查收邮箱。

**Comment by cccccs** [comment]
1312463385@qq.com 您好，有空能发给我一份吗 谢谢

**Comment by KJGithub2021** [comment]
@JasonForJoy can you please email me the script that creates the concatenated 100-dimensional word-2-vec (trained on UDC) plus 300-dimentional GLOVE embeddings ? I shall be really thankful. Email where to send: khadija.saeed@gmail.com
